name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Tag'
        required: true

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: ncipollo/create-release@v1.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ inputs.release_version }}
          release_name: Release v${{ inputs.release_version }}
          draft: false
          prerelease: false
          generateReleaseNotes: true
